### ISSUE TITLE
Overriding engagement end date

### ISSUE THREAD

**Issue by jamiesonio** [MaibornWolff/dd-import#72]
Hi Team,

Thank you for all your work on this tool. I was wondering why the engagement end date for engagements created by the import are defaulted to the year 2999, I am new to DefectDojo and was wondering if this was a best practice or intended workflow for CI/CD engagements. I see the code here is where these values are being defined https://github.com/MaibornWolff/dd-import/blob/main/dd_import/dd_api.py#L103-L104, happy to put in a PR to make these environment variables as it serves my use case but was looking for more insight into why this was setup this way. 

Best,
J

**Comment by jamiesonio** [comment]
I added a PR here for this functionality, please decline if its not desired
https://github.com/MaibornWolff/dd-import/pull/73/

**Comment by StefanFl** [comment]
Hi @jamiesonio, thank you for your PR. I will have a look at it as soon as possible.

**Comment by StefanFl** [comment]
Hi @jamiesonio, I have changed the second environment variable to `DD_ENGAGEMENT_TARGET_END` so that it matches the parameter of DefectDojo.

Your change has been released today with release 1.0.9.
