### ISSUE TITLE
automatically create Product Type in DefectDojo

### ISSUE THREAD

**Issue by tomaszn** [MaibornWolff/dd-import#97]
Hi, firstly, thank you for creating and maintaining this project.

I'd like to request a feature: project types are created automatically, if they are missing.

I'm using GitLab groups as Product Types. My users like to create new groups regularly. It would be great if this synced automatically.

If you are fine with this idea, I'm happy to contribute appropriate changes.

**Comment by StefanFl** [comment]
Hi @tomaszn, sounds like it makes sense. I am looking forward to your contribution.
